### PR TITLE
Add config file for nvr4xxx-4K

### PR DESCRIPTION
**Pull request by thanhdiepts**

### CODE REVIEW

**Comment by BotoX** [comment]
I think you used the erasesize on your config,
Can you paste cat /proc/mtd

Edit: Wow, you just put cramfs everywhere lol.
That's just wrong.

**Comment by thanhdiepts** [comment]
(none) login: admin
Password:
~ # cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00080000 00010000 "boot"
mtd1: 01700000 00010000 "rootfs"
mtd2: 00380000 00010000 "web"
mtd3: 00080000 00010000 "custom"
mtd4: 000c0000 00010000 "logo"
mtd5: 00140000 00010000 "config"
mtd6: 00280000 00010000 "misc"
~ #

It is cramfs Botox, base on the firmware extracted file..

**Review by thanhdiepts — COMMENTED** [review]
Update mtd size

**Comment by BotoX** [comment]
looks correct

**Pull request merged**
